---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php8.1
  name: phpcs
- commands:
  - vendor/bin/phan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1-ast
  name: phan
- commands:
  - ./vendor/bin/phpstan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1 lowest
steps:
- commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.2
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: bbd1d41f9ed656107b115dc777b3b79b73ccd3049b184bedbab77e3685838cc2

...
